package sgen

import (
	"github.com/rtjhie/sgen/examples/basic/sgen/internal/binjson"
)

// Do not edit this file. This file is generated by sgen.

type User struct {
	Name    string  `json:"name"`
	Address Address `json:"address"`
}

type Address struct {
	Street     string `json:"street"`
	City       string `json:"city"`
	Province   string `json:"province"`
	PostalCode string `json:"postal_code"`
}

// JSONSchema returns an embedded json file.
func (User) JSONSchema() []byte {
	return binjson.MustAsset("json/user.json")
}
