package sgen

import "github.com/rtjhie/sgen/examples/basic/sgen/internal/bindata"

// Do not edit this file. This file is generated by sgen.

// TODO: where do we run the cmd below?
// go run github.com/go-bindata/go-bindata/go-bindata -o=examples/basic/sgen/internal/bindata/bindata.go -pkg=bindata ./examples/basic/sgen/user.json

type Address struct {
	Street     string `json:"street"`
	City       string `json:"city"`
	Province   string `json:"province"`
	PostalCode string `json:"postal_code"`
}

type User struct {
	Name    string  `json:"name"`
	Address Address `json:"address"`
}

// JSONSchema returns an embedded json file.
func (u User) JSONSchema() []byte {
	b, err := bindata.Asset("examples/basic/sgen/user.json")
	if err != nil {
		return nil
	}
	return b
}
